version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "11:00"
      timezone: "America/Chicago"
    open-pull-requests-limit: 2
    commit-message:
      prefix: "dep upgrades: "
    labels:
      - "dependencies"
      - "docker"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "11:00"
      timezone: "America/Chicago"
    open-pull-requests-limit: 1
    commit-message:
      prefix: "ci upgrades: "
    labels:
      - "dependencies"
      - "github-actions"
    groups:
      github-actions:
        patterns:
          - "*"
